---
packages:
  discord:
    type: direct_url
    config:
      url: https://discord.com/api/download?platform=linux&format=deb

  draw.io:
    type: github_release
    download_should_fail: true
    config:
      repository: jgraph/drawio-desktop
      asset_name_pattern: -amd64-.+\.deb$

  heroic:
    type: github_release
    config:
      repository: Heroic-Games-Launcher/HeroicGamesLauncher
      asset_name_pattern: -amd64\.deb$

  lutris:
    type: github_release
    config:
      repository: lutris/lutris
      asset_name_pattern: _(all|amd64)\.deb$

  pandoc:
    type: github_release
    config:
      repository: jgm/pandoc
      asset_name_pattern: -amd64\.deb$

  rustdesk:
    type: github_release
    config:
      repository: rustdesk/rustdesk
      asset_name_pattern: -x86_64\.deb$

  spotube:
    type: github_release
    config:
      repository: KRTirtho/spotube
      asset_name_pattern: -x86_64\.deb$

  webos-dev-manager:
    type: github_release
    config:
      repository: webosbrew/dev-manager-desktop
      asset_name_pattern: _amd64\.deb$
